//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papaBobsPersistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        public System.Guid orderID { get; set; }
        public papaBobs.DTO.Enums.SizeType size { get; set; }
        public papaBobs.DTO.Enums.crustType crust { get; set; }
        public bool sausage { get; set; }
        public bool pepperoni { get; set; }
        public bool onions { get; set; }
        public bool greenPeppers { get; set; }
        public decimal totalCost { get; set; }
        public string customerName { get; set; }
        public string customerAddress { get; set; }
        public string customerZip { get; set; }
        public string customerPhone { get; set; }
        public papaBobs.DTO.Enums.paymentType paymentType { get; set; }
        public bool completed { get; set; }
    }
}
